### ISSUE TITLE
Relayprovider library isn't recognizing relayUrl for connecting with RelayServer.

### ISSUE THREAD

**Issue by dev1644** [tabookey/tabookey-gasless#166]
`RelayProvider` library accepts config with options of `RelayClient`, `RelayClient` accepts `relayURL` to connect with RelayHttpServer exposed on endpoint other than `localhost:8090`.

But currently, when passing `relayUrl` to RelayProvider doesn't do that, RelayProvider still tries to connect on `localhost:8090` even after providing different endpoint.

**Comment by drortirosh** [comment]
Connecting directly a relayUrl is a deprecated feature. 
The client should use only urls of registered relays, from the blockchain.
Accessing an unregistered relay will cause the request to fail, since the RelayHub will reject it.
We do have an open issue to allow the client to filter and use specific relay - but again, only from registered ones.
