### ISSUE TITLE
refactor (and reduce) parameters of IRelayRecipients

### ISSUE THREAD

**Issue by drortirosh** [tabookey/tabookey-gasless#185]
Parameters of `acceptRelayCall`/`preRelayedCall`/`PostRelayedCall` are repeated excessively. 
Its very difficult to share calculations between these methods: each as to re-calculate based on the transaction raw parameters.
This has gas implications, both in CPU (calculations) and data (passing a lot of useless parameters to all these methods)

Instead, we suggest that:

- `acceptRelayCall` should receive all parameters, and `returns (bytes context)`.
   Its failure status should be returned using "revert" (if not possible, then first uint in the bytes structure should be its return value, but its better if not..)
- `preRelayedCall` should receive this `context` variable, and can use it to pre-charge the user.
- `postRelayedCall` should receive the `context`, `gasUsed` and `preRelayedRetVal`, and can use these to charge/refund the user.

With this model, calculations can be done in advance, and their digested outputs shared by these methods.
Any extraction required from the **msgdata** (which might be large)- either for authentication or for actual user billing - will be done in the `acceptRelayedCall`, and only its outcome written into the `context`.

- A "free" RR would reduce gas cost of pre/post (which do nothing) - since they get much less parameters (and the `context` will be empty)
- A "Pay With Tokens" RR will extract needed information in acceptRelayedCall (e.g. calculate gas-to-token and address-to-charge), and pass only that information to `pre`,`post`. 

#### Cons:
- The methods now has to use encode/decode a context into `bytes` blob.
- There is an issue that we need to raise the gas-limit of `acceptRelayedCall`, as it might do little more stuff that it used to.

**Comment by spalladino** [comment]
I like the proposal, Dror! Each RR could define its own `Context` struct, and encode/decode it as needed. However, given that this is a major change, I'd suggest deferring it to a subsequent release. I think that we will get a lot of feedback from this version, and we can bundle this change along with others.

**Comment by drortirosh** [comment]
Yes, but it also makes a lot of your current changes redundant.

**Comment by shahafn** [comment]
@spalladino we already have PR #181 changing all the parameters of these functions. We might as well have this change instead since this PR needs fixing anyway.

**Comment by spalladino** [comment]
True, but #181 is already implemented, that's why I'd push that one instead!

**Comment by drortirosh** [comment]
The point is that #181 started small, just add free items, and ended up a mammoth, because of stack and gas issues.

**Comment by spalladino** [comment]
If I understand correctly, most of the complexity of #181 came from having to introduce the `ABIEncoderV2`, due to having too many parameters in those 3 methods. However, if we are passing all params to `acceptRelayCall`, we'll be in the same situation - the mammoth may be a little less woolly, but be a mammoth nonetheless.

**Comment by drortirosh** [comment]
No. `acceptRelayCall` was fine before, and even had an unused paramter - the `signature`. 
@nventuro added a parameter he thinks is important - the `maxCalculatedCharge`.
We argue that this parameter is not needed - though the new helper function to **calculate** is it important

The need for the encoded structure was the added parameters (also added to pre/post), not the existing ones.

**Comment by spalladino** [comment]
I understand that there were more parameters added to `acceptRelayCall`, namely `gasLimit` (which is needed to calculate the `maxCalculatedCharge`) and `nonce` (needed to prevent replays). 

That said, I'm not sure if just removing `maxCalculatedCharge` is enough to drop the EncoderV2. @nventuro could you confirm?

**Comment by yoav-tabookey** [comment]
I like this proposal.  It gives more flexibility to different models, and simplifies our current implementation.

In a non-blockchain project, I might think that it can be pushed to the next version, but since our "clients" are smart contracts, most of which don't have an easy upgrade path, I think it's worth considering this change for the oncoming release.  Once dapp developers build stuff for the previous model, it'll be harder to switch to this.  Unless we see a downside in switching to this model, let's do it.

Anyone sees a major downside?

As for encoding/decoding, another option would be to pass a "pointer", storing things temporarily in the RelayRecipient's storage, and freeing it at the end of the transaction.  It doesn't even need to be a mapping, since it's only used in the context of the current transaction.  Recipient could keep a Context struct locally, fill it during acceptRelayCall, use it later, and zero it at postRelayedCall.  No need to pass that arg to pre and post in this case, since it already has enough context.

The downside I see for my suggestion above, is that gas cost may be a bit higher, since we use storage (even though we free it at the end of the transaction).  But there's a security upside.  It becomes harder to write a vulnerable RelayRecipient in some cases:

The RelayRecipient functions can be called by anyone, not necessarily RelayHub, and the pre/post functions manipulate the contract's state, so if they rely on a Context they're given (or a list of args they're getting in our current model), they may be tricked to do the wrong thing.  Best practice would be to have a RelayHubOnly() modifier in RelayRecipient, and use it for all these functions, but we can't enforce that.

By using an internal context rather than passing args around, we deprive attackers from the ability to mess with pre/post.  Attacker may still try to trick acceptRelayCall, calling it with bad args that end up in the context, but it's a single point, so it's easier to protect.  We would offer setContext()/getContext() functions, to be used in accept/pre/post, and have these functions check that msg.sender is RelayHub.  A fake RelayHub calling acceptRelayCall (or pre/post for that matter) would get reverted in setContext/getContext.  Therefore, pre/post would be able to trust the context they get via getContext().

Does that make sense?

**Comment by nventuro** [comment]
>That said, I'm not sure if just removing maxCalculatedCharge is enough to drop the EncoderV2. @nventuro could you confirm?

The encoder had to be added because `atomicRecipientCalls` needed extra data to pass around to `pre` and `post` (`gasPrice`, among others). Adding a `context` variable will likely have a similar effect and not change the situation, though I guess we won't really know until we try.

>The point is that #181 started small, just add free items, and ended up a mammoth, because of stack and gas issues.

I'd argue that #181 is not a mammoth: it is paying a lot of technical debt (the creation of a proper `IRelayHub` interface contract, encapsulation of private constants, removal of duplicated API surface, fixes over gas estimations) that we didn't _have the need_ to fix before this point. Even if the recipient interface wasn't the one proposed there, those improvements should still be applied.

----

>Anyone sees a major downside?

A side-effect of passing a user-controlled array around is that the minimum gas stipend for `relayCall` is no longer deterministic: a recipient may cause an otherwise valid call to run out of gas, opening a new avenue of attack to honest relays.

I'd also like to mention that `RelayHub` is _very_ close to the absolute maximum contract size: 200 bytes more of bytecode will make the contract non-deployable without some re-architecturing that splits it over separate contracts, a non-trivial effort. I'd therefore be very wary of any changes that are not strictly required/bugfixes.

>Best practice would be to have a RelayHubOnly() modifier in RelayRecipient, and use it for all these functions, but we can't enforce that.

We already ask our users to never use `msg.sender` or `msg.data`, which is a _major_ requirement, and has direct security and consistency implications. A GSN contract will always require dedicated tooling (to fund the recipient, to interact with relays, etc.). Adding to these toolset a linter of sorts that warns on incorrect usage of `msg.sender`/`data` and lack of a `RelayHubOnly()` modifier is very feasible.

Regarding using the Hub's storage, that would probably be prohibitively expensive, considering the cost of using each slot of storage, and of calling back into the contract.

**Comment by yoav-tabookey** [comment]
> A side-effect of passing a user-controlled array around is that the minimum gas stipend for `relayCall` is no longer deterministic: a recipient may cause an otherwise valid call to run out of gas, opening a new avenue of attack to honest relays.
> 

With what I suggested above, we don't pass it around. Context is created inside the Recipient, in acceptRelayCall, and gets stored there. It is later accessed in pre/post, then freed in post. It's not user-controlled, since it's created by Recipient, and never passed back to RelayHub.  It's completely internal to Recipient.

> I'd also like to mention that `RelayHub` is _very_ close to the absolute maximum contract size: 200 bytes more of bytecode will make the contract non-deployable without some re-architecturing that splits it over separate contracts, a non-trivial effort. I'd therefore be very wary of any changes that are not strictly required/bugfixes.

You're definitely right that we shouldn't add code that takes us beyond the max contract size. But my suggestion actually reduces the amount of code. We won't need to pass all these args from RelayHub to Recipient, since Recipient gets it once (in acceptRelayCall) and maintains it for the rest of the transaction. Less code around calling pre/post, no new code added to RelayHub.  We do end up adding some code to RelayRecipient (three simple functions, getContext/setContext/freeContext) but I think that's not a problem.

> We already ask our users to never use `msg.sender` or `msg.data`, which is a _major_ requirement, and has direct security and consistency implications. A GSN contract will always require dedicated tooling (to fund the recipient, to interact with relays, etc.). Adding to these toolset a linter of sorts that warns on incorrect usage of `msg.sender`/`data` and lack of a `RelayHubOnly()` modifier is very feasible.

A linter for those things is a great idea!

> Regarding using the Hub's storage, that would probably be prohibitively expensive, considering the cost of using each slot of storage, and of calling back into the contract.

I wasn't suggesting using Hub's storage, but Recipient's.  Recipient gets all the data it needs in acceptRelayCall, takes whatever it needs from it, and passes it to setContext() which is implemented in RelayRecipient.sol.  setContext() stores it locally, doesn't call back into Hub.  It does, however, require(msg.sender == RelayHub), to ensure that setContext() is only called with trusted args that came from RelayHub.  Then, pre and post use getContext() to use that trusted context.  At the end of post, it is advised to call freeContext() which zeros the local context storage, to reduce gas costs.  (this is not a security thing, since setContext() in the next transaction will overwrite it anyway).

So we don't use Hub storage, and we don't use any inter-transaction storage.  We only use some Recipient storage, intra-transaction.

**Comment by nventuro** [comment]
Ah, my bad: I must've misread your original comment  and misunderstood that bit of your proposal. Using `accept` that way wouldn't work because it is called with `staticcall`, so writes to storage are disallowed.

**Comment by yoav-tabookey** [comment]
The staticcall problem could be mitigated by making setContext() a public function that requires msg.sender==RelayHub.  acceptRelayCall would return a value, which RelayHub would immediately pass to RelayRecipient.setContext() for storage.  Recipient would make sure it came from RelayHub, store it, and later access it from pre/post as needed.

You're right that the gas cost is higher, although I don't think it should cost 10k.  It's used intra-transaction and gets refunded at the end of the transaction when freeContext() is called.  Isn't that 5000 rather than 10000?  (but yes, 5000 is still not cheap)

**Comment by nventuro** [comment]
>You're right that the gas cost is higher, although I don't think it should cost 10k. It's used intra-transaction and gets refunded at the end of the transaction when freeContext() is called. Isn't that 5000 rather than 10000? (but yes, 5000 is still not cheap)

An `sstore` that changes storage from zero to non-zero costs 20k, and one that changes it back to zero costs 5k and refunds 15k, so fully refunded `sstore`s costs 5k each. [EIP1283](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1283.md) aimed to enable use cases like the one you proposed, but was taken out of Constantinople due to security concerns.
