### ISSUE TITLE
Missing support of eth_sendRawTransaction

### ISSUE THREAD

**Issue by k06a** [tabookey/tabookey-gasless#210]
Why you don't `eth_sendRawTransaction`?

**Comment by k06a** [comment]
We need to use privateKey with web3 and can't make your provider work.

**Comment by drortirosh** [comment]
Not sure exactly what you mean?
sendRawTransaction is a way to send an ethereum signed transaction, which means *you pay for it*.
If you want to send it through a relay, you signed a *relay transaction* (by calling `RelayClient.relayTransaction`, directly or using `RelayProvider` to do it for you)
This way, it is signed all the way to the relay, and the relay will create the signed ethreum transaction (and pay for it in ether)
BTW: the relay actually returns this signed transaction to the client.

**Comment by drortirosh** [comment]
If you want to specify your own private key , then you use :
`RelayClient.useKeypairForSigning()`, which is given `{address, privateKey}`
You can use `RelayClient.newEphemeralKeypair()` to create such key pair, or create your own.

*IMPORTANT*
when sending this transaction, make sure to specify `{ from: keypair.address }`, so that the "from" field is indeed the address matching the privatekey.
forgetting to do so will return "invalid signature" from the relay .

**Comment by shahafn** [comment]
@k06a can you please elaborate on what you meant?

**Comment by k06a** [comment]
We used web3 to sign transactions on the client side, not found `RelayClient.useKeypairForSigning()` method and solved problems by adding `eth_sendRawTransaction`: https://github.com/tabookey/tabookey-gasless/pull/211

**Comment by k06a** [comment]
I think you could deprecate `RelayClient.useKeypairForSigning()`, because it is doubling web3 functionality.

**Comment by drortirosh** [comment]
> I think you could deprecate `RelayClient.useKeypairForSigning()`, because it is doubling web3 functionality.

`web3.eth.sign` will prompt the user to sign - which might be OK in some situations.
When you provide your keypair (created with `newEphemeralKeypair()`, or by other means), you sign with it without prompting the user each time.
This gives better user experience, and let you work even without Metamask or other wallet installed in your browser (though its clearly less secure)

**Comment by drortirosh** [comment]
Also note that we sign *relayed* transaction - which contains also the relay to use and the transaction-fee we agree to pay.
normal "signed transaction" doesn't let the user to provide and sign these items.

These are required so that the relay won't attempt to rob the client (e.g. by specifying a huge transaction fee). We actually check on-chain (in the RelayHub) that the relay conveyed the user's request as-is, without modifications. For that we need the user to sign all this information (even though he doesn't pay for the transaction)
