### ISSUE TITLE
relayTransaction: Recipient balance too

### ISSUE THREAD

**Issue by k06a** [tabookey/tabookey-gasless#212]
I see following error. It seems it tries to use 343 Gwei gasPrice for some reason:

>nextRelay: find fastest relay from: [{"address":"0x2BF1Ce7D6F81C2cc9885DA5b501614C1107Ca39e","relayUrl":"https://mainnet-03.gsn.openzeppelin.org","transactionFee":"70","stake":"1000000000000000000","unstakeDelay":"604800","score":930}]

>getRelayAddressPing URL: https://mainnet-03.gsn.openzeppelin.org

>race finished with a champion: https://mainnet-03.gsn.openzeppelin.org

>relayTransaction hash:  0x4663436608440525f7f9e2655033ad9f2c8ef65baabcd5f35478898145b0fef2 from:  0x261CCfc2f9FA24Ae93c18D379a78c597C2eC8700 sig:  0x3576de481c17896749273da6e20da6d21314d92fdb5b0c0c48069cc67caaf0495c56b15b75b03cb80549059c9ea96a8123c52855092d3608d0bc62317aaf22f21c

>relayTransaction recovered: 0x261ccfc2f9fa24ae93c18d379a78c597c2ec8700 signature is correct

>sendViaRelay to URL: https://mainnet-03.gsn.openzeppelin.org {"encodedFunction":"0x2d1e0c02000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000507690e828ccb9043220189ba30c6e7b9723c5c8fce3d9d341343aa91e3885be722174a4f3ef698052562e5c1ea9d60ff2761c5b19bbba37aee3495c583067c46b6d26c044dfe8ee27460b3e8a40c3314400000000000000000000000000000000","signature":"0x3576de481c17896749273da6e20da6d21314d92fdb5b0c0c48069cc67caaf0495c56b15b75b03cb80549059c9ea96a8123c52855092d3608d0bc62317aaf22f21c","approvalData":[],"from":"0x261CCfc2f9FA24Ae93c18D379a78c597C2eC8700","to":"0xce3f913E70A936Cd84BE5D75352279E0B2C027Eb","gasPrice":343597383680,"gasLimit":1048576,"relayFee":70,"RecipientNonce":0,"RelayMaxNonce":55,"RelayHubAddress":"0xD216153c06E857cD7f72665E0aF1d7D82172F494"}

>sendViaRelay resp= {error: "Recipient balance too low: 50000000000000000, maxCharge: 845086698692935680"}

>relayTransaction: req: {from: "0x261CCfc2f9FA24Ae93c18D379a78c597C2eC8700", to: "0xce3f913E70A936Cd84BE5D75352279E0B2C027Eb", encodedFunctionCall: "0x2d1e0c020000000000000000000000000000000000000000…7460b3e8a40c3314400000000000000000000000000000000", txfee: undefined, gasPrice: 343597383680, …}

>relayTransaction: Recipient balance too
>low:  50000000000000000,
>maxCharge:  845086698692935680

>RR error:  Error: No relay responded! 3 attempted, 3 pinged
>    at RelayClient.relayTransaction (RelayClient.js:321)

**Comment by drortirosh** [comment]
your client agreed to pay gasPrice of 343597383680 - which means that what `web3.eth.getGasPrice()` returned at that moment.
The relay wouldn't mine to create a transaction with such high gas price - but it found out your recipient didn't have enough deposit (on relay hub) for the possible max charge, so it rejected the transaction.

1. Probably you want to place a "cap" on what gas price to use: in each transaction you can specify `{ gasPrice: xxx }` - or wait and send the transaction later. 
2. alternately, you can increase the deposit on the relay hub

NOTE: normal ethereum transaction can be sent with low gas price, with the expectation to stay in the mempool until some relay would agree to send them (or not)
With the relay network, each relay defines the minimum gas price it agrees to use for a transaction, and it will refuse to send the request if you specify lower gas price (this is OK, since sending with a low gas price means the relay is blocked from sending other requests until that one gets mined)
So if you want to wait for a lower gas price, you have to do that in the client.

**Comment by k06a** [comment]
We found and fixed this bug. We added eth_sendRawTransaction handling to your provider, and decoded tx in a wrong way. Already fixed, see our PR #211
