### ISSUE TITLE
Working Explanation

### ISSUE THREAD

**Issue by chaitanyapotti** [tabookey/tabookey-gasless#244]
The RelayHub Contract expects the return from the static call of `acceptRelayedCall` to be [(bool, bytes)](https://github.com/tabookey/tabookey-gasless/blob/master/contracts/RelayHub.sol#L228) whereas the underlying interface returns [(uint256, bytes)](https://github.com/tabookey/tabookey-gasless/blob/master/contracts/IRelayRecipient.sol#L48). 

Can someone explain how it is working right now with this mismatched interface or am i referencing something wrong?

**Comment by sshelton76** [comment]
I believe it's because 0 is considered true and all other conditions are false when casting a uint to a bool.

Look at GSNBouncerBase for examples, it's allowing you to return either true "0" or an error with an inbuilt reason code.

This is historically how it's done...
https://en.wikipedia.org/wiki/Exit_status

**Comment by shahafn** [comment]
I believe that you are conflating the return value of evm instruction `call` which is `(bool,bytes)` and `acceptRelayedCall`'s return value which is decoded from the generic bytes which `call` returns. The bool is the revert status of the external call, we use this pattern of catching reverts of external calls all over `RelayHub` to protect the relayer.

**Comment by chaitanyapotti** [comment]
@shahafn Thanks for the explanation.
