### ISSUE TITLE
No default txfee

### ISSUE THREAD

**Issue by alex-forshtat-tbk** [tabookey/tabookey-gasless#58]
When using the RelayProvider, we MUST specify "txfee".
Without it, the client will create a transaction with ZERO "txfee" and almost definitely will fail to find a relay.

Steps to reproduce:

1. Checkout https://github.com/tabookey/metacoin, branch "with-relay"
2. remove 'txfee' value
3. npm run dev

Expected:
The transaction completes successfully

Actual:
The transaction fails, having 0 as "txfee"

**Comment by drortirosh** [comment]
default txfee should be the published fee by the given relay. Any other value is not good as default:
- lower default value is bad, since its going to be rejected by the relay
- higher value means we "overpay" the relay more than it asked for.

While a client SHOULD be able to explicitly specify a txfee (e.g. it really want to overpay) - it must not be the default

**Comment by drortirosh** [comment]
fixed in #170
